services:
  postgres:
    image: postgis/postgis:15-3.3
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 10
      start_period: 20s

  postgres-init:
    image: postgis/postgis:15-3.3
    restart: "no"
    environment:
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
      PGHOST: postgres
      PGPORT: 5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: |
      bash -ec '
        until pg_isready -h $$PGHOST -U $$PGUSER -d $$PGDATABASE; do sleep 1; done
        psql -h $$PGHOST -U $$PGUSER -d $$PGDATABASE -f /docker-entrypoint-initdb.d/init.sql
        echo "INIT DONE"
      '

  redis:
    image: redis:7-alpine
    command: redis-server --save "" --appendonly yes
    volumes:
    - ./redis:/data


  app:
    build: ./app
    restart: unless-stopped
    env_file: .env
    environment:
      PYTHONUNBUFFERED: 1 
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      postgres-init:
        condition: service_completed_successfully
    ports:
      - "8000:8000"  # <-- Only API should be public
    volumes:
      - ./logs:/logs
      - ./reports:/reports


  worker:
    build: ./app
    restart: unless-stopped
    env_file: .env
    environment:
      PYTHONUNBUFFERED: 1 
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      postgres-init:
        condition: service_completed_successfully
    command: ["python", "-m", "worker"]
    volumes:
    - ./logs:/logs
    - ./reports:/reports


  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  pgdata:
